# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2024.03.1
_src_path: gh:astrojuanlu/copier-pylib
author_email: hello@juanlu.space
author_name: Juan Luis Cano Rodríguez
github_org: astrojuanlu
package_name: desalkila
project_name: desalkila
short_description: (TBC)
